#!/bin/sh
set -e

if [ -d /run/systemd/system ]; then
  deb-systemd-invoke stop mboard >/dev/null || true
  if deb-systemd-invoke is-enabled mboard >/dev/null
  then
    deb-systemd-invoke disable mboard >/dev/null || true
  fi
fi

if [ -d /home/mboard/bin ]; then
  rm -rf /home/mboard/bin
  rm -rf /home/mboard/data
  rm -rf /home/mboard/.config
  rm -rf /etc/systemd/system/multi-user.target.wants/mboard.service
fi

exit 0
